apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.18.19.238
    path: "/home/ubuntu/nfsshare"
  mountOptions:
    - nfsvers=4.2
