kind: PersistentVolumeClaim
apiVersion: v1
metadata:
        name: sc-pvc
spec:
        accessModes:
                - ReadWriteMany
        storageClassName: "nfs-client"
        resources:
                requests:
                        storage: 1Gi
