apiVersion: v1
kind: Service
metadata:
  name: nginx-ui
  labels:
    app: nginx-ui
spec:
  type: ClusterIP
  ports:          
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ui
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-ui
spec:
  selector:
    matchLabels:
      app: nginx-ui
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx-ui
    spec:
      containers:
      - name: nginx-ui
        image: nginxdemos/hello
        ports:
        - containerPort: 80
