apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser-app
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: taipower-harbor.zerone.lab/taipower/filebrowser:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        name: http
        volumeMounts:
        - mountPath: /data
          name: data1
      volumes:
      - name: data1
        persistentVolumeClaim:
          claimName: demo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: filebrowser
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-ingress
spec:
  rules:
  - host: filebrowser.taipower.zerone.lab
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: filebrowser
            port:
              number: 80
