apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ui
  labels:
    app: nginx-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ui
  template:
    metadata:
      labels:
        app: nginx-ui
    spec:
      containers:
      - name: nginx-ui
        image: nginxdemos/hello
        ports:
        - containerPort: 80
          protocol: TCP
        name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ui
  labels:
    app: nginx-ui
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx-ui
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ui-ingress
spec:
  rules:
  - host: nginx-ui.zodemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx
            port:
              number: 80
