kind: PersistentVolumeClaim
apiVersion: v1
metadata:
        name: nfs-pvc
spec:
        accessModes:
                - ReadWriteMany
        storageClassName: ""
        resources:
                requests:
                        storage: 1Gi
