apiVersion: v1
kind: PersistentVolume
metadata:
        name: nfs-pv
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        nfs:
                server: 10.8.7.174
                path: /var/nfsshare
